var config = {
    "ranks": {
        "Lieutenant Required": [
            { "id": 7, "name": "Spawn Beacon", "section": "Squad" },
            { "id": 6003089, "name": "Ambusher Jump Jets 1", "section": "Light Assault" },
            { "id": 1630, "name": "Medical Applicator 6", "section": "Combat Medic" },
            { "id": 8658, "name": "Nano-Regen Device 5", "section": "Combat Medic" },
            { "id": 884, "name": "Nanite Revive Grenade", "section": "Combat Medic" },
            { "id": 8124, "name": "Flak Armor 4", "section": "Combat Medic" },
            { "id": 6010, "name": "Nano-Armor Kit 6", "section": "Engineer" },
            { "id": 6004531, "name": "Reserve Hardlight Barrier", "section": "Engineer" },
            { "id": 35004, "name": "Nemesis VSH9", "section": "Heavy Assault" },
            { "id": 7696, "name": "Flak Armor 4", "section": "Heavy Assault" },
            { "id": 17000, "name": "Quasar VM1 (primary)", "section": "MAX" },
            { "id": 17012, "name": "Quasar VM1 (second)", "section": "MAX" },
            { "id": 17024, "name": "or Nebula VM20 (second)", "section": "MAX" },
            { "id": 7520, "name": "or Cosmos VM3 (second)", "section": "MAX" },
            { "id": 7525, "name": "or Blueshift VM5 (second)", "section": "MAX" },
            { "id": 2847, "name": "Gate Shield Diffuser 2", "section": "Sunderer" },
            { "id": 3098, "name": "Deployment Shield 1", "section": "Sunderer" }
        ],
        "Lieutenant Recommended Infantry": [
            { "id": 472, "name": "Recon Detection Device 1", "section": "Infiltrator" },
            { "id": 50051, "name": "EMP Grenade", "section": "Infiltrator" },
            { "id": 1045, "name": "Proximity Mine", "section": "Infiltrator" },
            { "id": 432, "name": "C-4 (check)", "section": "Light Assault" },
            { "id": 0, "name": "Drifter Jump Jets 1", "section": "Light Assault" },
            { "id": 0, "name": "Hunter QCX", "section": "Light Assault" },
            { "id": 0, "name": "Explosive Bolt", "section": "Light Assault" },
            { "id": 0, "name": "Grenade Bandolier 3", "section": "Combat Medic" },
            { "id": 0, "name": "Nano-Regen Device 6", "section": "Combat Medic" },
            { "id": 0, "name": "C-4", "section": "Combat Medic" },
            { "id": 0, "name": "Flak Armor 5", "section": "Combat Medic" },
            { "id": 202, "name": "Anti-Infantry MANA Turret", "section": "Engineer" },
            { "id": 0, "name": "Tank Mine", "section": "Engineer" },
            { "id": 0, "name": "Lasher X2", "section": "Heavy Assault" },
            { "id": 0, "name": "Concussion Grenade", "section": "Heavy Assault" },
            { "id": 0, "name": "Grenade Bandolier 3", "section": "Heavy Assault" },
            { "id": 0, "name": "C-4", "section": "Heavy Assault" },
            { "id": 0, "name": "Flak Armor 5", "section": "Heavy Assault" },
            { "id": 0, "name": "NS-10 Burster", "section": "MAX" }
        ],
        "Lieutenant Recommended Armour": [
            { "id": 3441, "name": "E540 Halberd", "section": "Harasser" },
            { "id": 0, "name": "Fire Suppression 1", "section": "Harasser" },
            { "id": 0, "name": "Vehicle Stealth 1", "section": "Harasser" },
            { "id": 0, "name": "Racer High Speed Chassis 1", "section": "Harasser" },
            { "id": 3086, "name": "Primary G40-F Ranger", "section": "Deployment Sunderer" },
            { "id": 3089, "name": "Secondary G40-F Ranger", "section": "Deployment Sunderer" },
            { "id": 3003, "name": "Fire suppression 1", "section": "Deployment Sunderer" },
            { "id": 3098, "name": "Deployment Shield", "section": "Deployment Sunderer" },
            { "id": 802791, "name": "Stealth Cloaking Module", "section": "Deployment Sunderer" },
            { "id": 3056, "name": "Racer High Speed Chassis 1", "section": "Deployment Sunderer" },
            { "id": 2800, "name": "Primary M12 Kobalt", "section": "GateShield Diffuser Sunderer" },
            { "id": 2806, "name": "Secondary M12 Kobalt", "section": "GateShield Diffuser Sunderer" },
            { "id": 2846, "name": "Gate Shield Diffuser 1", "section": "GateShield Diffuser Sunderer" },
            { "id": 2964, "name": "Nanite Proximity Repair System", "section": "GateShield Diffuser Sunderer" },
            { "id": 3056, "name": "Racer High Speed Chassis 1", "section": "GateShield Diffuser Sunderer" },
            { "id": 2803, "name": "Primary M20 Basilisk", "section": "Battle Bus Sunderer" },
            { "id": 2809, "name": "Secondary M20 Basilisk", "section": "Battle Bus Sunderer" },
            { "id": 3003, "name": "Fire suppression 1", "section": "Battle Bus Sunderer" },
            { "id": 2964, "name": "Nanite Proximity Repair System", "section": "Battle Bus Sunderer" },
            { "id": 3007, "name": "Blockade Armor 1", "section": "Battle Bus Sunderer" },
            { "id": 3056, "name": "Racer High Speed Chassis 1", "section": "Battle Bus Sunderer" },
            { "id": 6553, "name": "CAS 14-E", "section": "Valkyrie" },
            { "id": 6577, "name": "Scout Radar 1 (check)", "section": "Valkyrie" },
            { "id": 6581, "name": "Vehicle Stealth 1 (check)", "section": "Valkyrie" },
            { "id": 6590, "name": "Evasiveness Airframe 1", "section": "Valkyrie" },
            { "id": 5513, "name": "Top: A30 Walker", "section": "Galaxy" },
            { "id": 5513, "name": "Tail: A30 Walker", "section": "Galaxy" },
            { "id": 2832, "name": "Left: M60-G Bulldog (check)", "section": "Galaxy" },
            { "id": 2832, "name": "Right: M60-G Bulldog (check)", "section": "Galaxy" },
            { "id": 5529, "name": "Fire suppression 1", "section": "Galaxy" },
            { "id": 5731, "name": "Nanite Proximity Repair System 1", "section": "Galaxy" },
            { "id": 5275, "name": "Vehicle Stealth 1 (check)", "section": "Galaxy" },
            { "id": 5694, "name": "Racer High Speed Airframe 1", "section": "Galaxy" },
        ]
    }
};
